### ISSUE TITLE
remove setTimeout

### ISSUE THREAD

**Issue by desandro** [desandro/imagesloaded#1]
I added a `setTimeout` specifically for cloning/appending new elements in Chrome. It's a bit of a cheat, so we may want to remove it.

**Comment by OZZlE** [comment]
Would be great...

![skarmklipp 2018-11-05 11 15 08](https://user-images.githubusercontent.com/893783/47992030-2015bf80-e0ec-11e8-957c-5a9fb9497819.png)

      function onProgress( image, elem, message ) {
        // HACK - Chrome triggers event before object properties have changed. #83
        setTimeout( function() {
          _this.progress( image, elem, message );
        });
      }

**Comment by desandro** [comment]
I'm going to let this one go after 9 years.
