### ISSUE TITLE
Add method to abort loading

### ISSUE THREAD

**Issue by staaky** [desandro/imagesloaded#100]
It would be nice to have a method to abort loading so a callback is never reached, something like:

``` javascript
var loading = new imagesLoaded( elem, callback );
loading.abort();
```

**Comment by OZZlE** [comment]
If you want to use this lib in for example a SPA, if imagesLoaded hasn't finished when going away from the page you were at, then it continuous of elements that might not even exists anymore, and it reeks havoc on performance ./ so I'd say it's a pretty important feature..

**Comment by OZZlE** [comment]
Proposed fixes doesn't help either.
![skarmklipp 2018-11-05 10 46 44](https://user-images.githubusercontent.com/893783/47990575-25710b00-e0e8-11e8-92c0-b80790bdf11a.png)

**Comment by englishextra** [comment]
@OZZIE 

For SPAI use:

```js
		var onImagesLoaded = function (macy) {
			var img = macy[getElementsByTagName]("img") || "";
			var imgLength = img[_length] || 0;
			var imgCounter = 0;
			var onLoad;
			var onError;
			var addListeners = function (e) {
				addListener(e, "load", onLoad, false);
				addListener(e, "error", onError, false);
			};
			var removeListeners = function (e) {
				removeListener(e, "load", onLoad, false);
				removeListener(e, "error", onError, false);
			};
			onLoad = function () {
				removeListeners(this);
				imgCounter++;
				if (imgCounter === imgLength) {
					if (root.updateMacyThrottled) {
						updateMacyThrottled();
					}
					console.log("onImagesLoaded: loaded " + imgCounter + " images");
				}
			};
			onError = function () {
				removeListeners(this);
				console.log("onImagesLoaded: failed to load image: " + this.src);
			};
			if (img) {
				var i,
				l;
				for (i = 0, l = img[_length]; i < l; i += 1) {
					addListeners(img[i]);
				}
				i = l = null;
			}
		};
```

and I continue using `imagesLoaded` for regular sites.

**Comment by jesseenloe** [comment]
Closed as completed on Feb 8, 2022: How does one access this functionality? (I do not see it in the docs.) Thanks!
