### ISSUE TITLE
Your code doesn't specify a license

### ISSUE THREAD

**Issue by Lexicality** [desandro/imagesloaded#102]
Your code doesn't specify that it's licensed under the MIT License which leaves it as unlicensed as soon as it's separated from the github readme.

**Comment by surfmuggle** [comment]
Hello @desandro  the readme contains a chapter MIT license which states that imagesloaded uses the MIT license. But it does not contain a copyright. 

Two suggestions: 

 - include a license file (see below)
 - include a copyright notice

Thanks

### Copyright Notice

Mostly in [341](https://github.com/github/opensource.guide/pull/341)  it was debated if a copyright notice is needed (see also  [337](https://github.com/github/opensource.guide/pull/337) and  [343](https://github.com/github/opensource.guide/pull/343))

According to a github employee a copyrhight notice is not needed for countries that are part of TRIPS (see [341](https://github.com/github/opensource.guide/pull/341)). Nonetheless did our legal team point out that a copyright notices is missing. I am in discussion with them if it is a "nice to have" or mandatory. 

### Recommendation regarding license

The github opensource.guide [Launching your own open source project](https://opensource.guide/starting-a-project#launching-your-own-open-source-project)  links to [licensing a repository](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#where-does-the-license-live-on-my-repository)

> Most people place their license text in a file named LICENSE.txt (or LICENSE.md) in the root of 
> the repository; here's an example from Hubot.
> 
> [...]
> 
> As a best practice, we encourage you to include the license file with your project.

This is what our legal department (germany) prefers as well.
