### ISSUE TITLE
add clearCache method

### ISSUE THREAD

**Issue by hspinks** [desandro/imagesloaded#103]
First of all, let me say a huge THANK YOU for the imagesLoaded and Masonry modules - truly awesome, very easy to plug in and get started, and have significantly improved the design and development speed on my web projects.

I have run into a particular issue here with Rails 3.1, Unobtrusive JS submitting forms via Ajax, and imagesLoaded.

Essentially, I am displaying a grid of products with filters so you can display only the ones that fit certain criteria. A watered down version of the code that I use can be found [in this gist](https://gist.github.com/hspinks/7112821).

The search filter form sends its request to the same products page, and when it uses Ajax it responds with a JS file that replaces the HTML of a products-grid container with the new, matching products. Of course, the images for all of these products are different sizes, so I use Masonry to lay them out nicely, which works great on the initial Ajax-less page load. However, after getting the new set of products with Ajax, the imagesLoaded fires way too early, and I get a layout that is not very pretty.

I have done enough testing to know that the issue is not with Masonry, but with imagesLoaded. The simplest test that confirmed this was simply putting a longer timeout before calling Masonry, and when I did that, the Masonry laid the div out flawlessly.

I have isolated the issue to only occurring when it is **the same** images that are in both the initial HTML and the Ajax-loaded HTML. My guess is that imagesLoaded somehow caches whether or not these images have been loaded, and therefore does not do any sort of re-check when it sees the same image URL a second time.

Looking at the [imagesLoaded project page](http://desandro.github.io/imagesloaded/), I don't see anything that immediately jumps out at me as a solution, so I figured I would ask here:
Is there a way to reset the imagesLoaded module so that it doesn't "remember" whether the same image reloaded in the page has been rendered?

**Comment by cperryk** [comment]
I was facing a similar issue. The imagesLoaded callback was firing before the images themselves had dimensions in cases in which the images had been displayed before. But the no-cache branch resolved it.

**Comment by desandro** [comment]
imagesLoaded v3.2.0 has removed the cache. [Try it out](http://imagesloaded.desandro.com/#install). Closing this issue. :whale:
