### ISSUE TITLE
imagesLoaded() function not fire when going 'back' with iOS7

### ISSUE THREAD

**Issue by negatron** [desandro/imagesloaded#112]
Hello,

I don't know whether this a new issue for iOS7 (I can't currently test on 6) but when you navigate back a page in the Mobile Safari app using the native back button, the imagesLoaded() function does not fire and the functions within it are not triggered. (It works fine using the Chrome app on my iPhone).

The code I'm using looks like this:

`imagesLoaded( document.querySelector('#content'), function( instance ) {
		    console.log('images loaded');
	});`

I've been having no problems up until now (when I started testing on an iPhone).

Has this issue come up before (I can't see it mentioned anywhere) and is there a potential fix (ideally) or some kind of workaround anyone can think of?

Many thanks in advance,

ben

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like no one chimed in, so I'm closing this one.
