### ISSUE TITLE
loading cached svg images in ie in imagesloaded 2.1.2

### ISSUE THREAD

**Issue by jedierikb** [desandro/imagesloaded#118]
This is a report for an old version of imagesloaded (2.1.2)  but might be of help/interest to future developers who run into this problem.

imagesloaded did not properly support loading of cached svgs used as images on ie (e.g. ```javascript <img src="shape.svg">```.  This little bit of code helped to remedy this situation (with an existing function from the existing library to help with its position):

```javascript
if (el.complete && (!!el.src.match(/.svg$/) || !!el.src.match(/.svgz$/))) {
    imgLoaded( el, false );
    return;
}

// if complete is true and browser supports natural sizes, try
// to check for image status manually
if ( el.complete && el.naturalWidth !== undefined ) {
    imgLoaded( el, el.naturalWidth === 0 || el.naturalHeight === 0 );
    return;
}
```

**Comment by desandro** [comment]
imagesLoaded v3.2.0 has removed its internal cache. I'm closing this issue as resolved.
