### ISSUE TITLE
Using with browserify gives error

### ISSUE THREAD

**Issue by joaovpmamede** [desandro/imagesloaded#119]
I'm trying to require the script with browserify using this transform: 
https://github.com/eugeneware/deglobalify

Doing something like:

```
var imagesloaded = require('./imagesloaded.pkgd.min.js', ['EventEmitter, 'eventie', 'imagesLoaded']);
```

What happens is that I'm getting this error:

```
Uncaught TypeError: undefined is not a function 
```

here:

```
ImagesLoaded.prototype = new EventEmitter();
```

**Comment by ssathishkumar540** [comment]
Hi,
     i am also using bootstrap datetimepicker. In textbox it is showing "undefined". I ma using the latest version. Please help me. How can i resolve this?

**Comment by stianlp** [comment]
I am having this problem with v3.1.8

var imagesloaded = require('../bower_components/imagesloaded/imagesloaded');

gives the following error:

Error: Cannot find module 'wolfy87-eventemitter' from '/<path>/bower_components/imagesloaded'
Error: Cannot find module 'eventie' from '/<path>/bower_components/imagesloaded'
[Error: write after end]

**Comment by desandro** [comment]
@stianlp Try requiring `../bower_components/imagesloaded/imagesloaded.pkgd`

**Comment by stianlp** [comment]
@desandro Nope, still does not work.

Error: Cannot find module 'wolfy87-eventemitter' from '/<path>/bower_components/imagesloaded'
Error: Cannot find module 'eventie' from '/<path>/bower_components/imagesloaded'
