### ISSUE TITLE
Problems with FF 26 after chaging src atr. of an image

### ISSUE THREAD

**Issue by individual-it** [desandro/imagesloaded#121]
In my application I have to exchange an image constantly with a new one (webcam).
So I have 2 img  tags. While one image is shown the other is loaded. As soon the second image is loaded the first one is hidden and the second one is shown. Then again the first one gets a new src= and loads a new image. As soon as it finished it gets shown.
I'm using this plugin to see if the new image is loaded before I hide the first one and show the second one.

```
$('#imageFrame1_' + newImage).attr( "src", data.responseText );
var imgLoad = imagesLoaded( '#imageFrame1_' + newImage);
imgLoad.on( 'always', function( instance ) {
console.log('#imageFrame1_' + newImage + ' loaded ' + Date.now());
$('#imageFrame1_' + newImage).show();
$('#imageFrame1_' + currentImage).hide();
//more code here
}); 
```

the first time an image is loades "imgLoad.on" is fired correctly after the image loading is finished. But when I change the src, its fired immediately without waiting for the new image to be loaded.

This happens with Firefox 26.0 on Linux. Chrome works as it should.

**Comment by tilt-me** [comment]
@Kris-B 
Be careful, setting src of an image to an empty string can be dangerous for performance reasons:
[Empty image src can destroy your site](https://www.nczonline.net/blog/2009/11/30/empty-image-src-can-destroy-your-site/)

Don't know if it is still an issue for modern browsers, but I would avoid it anyway ;)
