### ISSUE TITLE
Synchronously test if image(s) is loaded?

### ISSUE THREAD

**Issue by nybblr** [desandro/imagesloaded#122]
I am using this plugin to show a loading animation for images in a slideshow: before fading to the next slide, I use imagesLoaded.done() on the particular slide.

Before creating the callback, I first show the loader. The done() callback hides it.

This works great when the next image in the slideshow is downloading: the loader shows and hides itself appropriately. However, once the images are already loaded, the loader "flickers" between slides because it is being shown, then immediately hidden in the done() callback. Since the callback isn't executed synchronously, the DOM has a chance to rerender before hiding the loader.

The resulting effect is an irritating flicker between every single slide. So it'd be nice to take advantage of the LoadingImage.prototype.check method to check if an image is already loaded (or failed to load) without handing the thread back to the browser for a rerender. Then I could check if the image is loaded before even showing the loader (and thus prevent the flicker altogether).

I know this can usually be done with `.complete` on the image node, but to my knowledge this has some compatibility issues; is this cross-browser logic already implemented in imagesLoaded? Could it be exposed for use?

Or, maybe an option could be passed in which makes imagesLoaded trigger the callbacks immediately (without giving up the main thread) if the image is loaded?

~ Jonathan

**Comment by desandro** [comment]
Sorry, but I will not be able to resolve this issue.

**Comment by rhys-vdw** [comment]
> I will not be able to resolve this issue.

@desandro This seems like a useful feature. I use `imagesLoaded` to toggle the class on an image that has loaded - allowing me to fade it in. If the image is already cached then it creates a very distracting effect where everything in the page will fade in after the page loads.

Just wondering what your reasoning was? (If you remember)
