### ISSUE TITLE
Listen to image loadings over time using streams

### ISSUE THREAD

**Issue by slorber** [desandro/imagesloaded#129]
Hello,

See this kind of related issue:
https://github.com/smidwap/wysihtml5_size_matters/issues/6

As you can see I'm using some code to resize an editor:

```javascript
      Wysihtml5SizeMatters.prototype.handleImagesLoading = function() {
        var _this = this;
        this.$body.imagesLoaded()
            .progress( function( instance, image ) {
              _this.adjustHeight();
            })
            .always(function( instance ) {
              _this.adjustHeight();
            });
      };
```

It would be cool if it was possible to, instead of using a deferred JQuery object, be able to listen to image loadings over time under a particular dom node.

Basically this would do:
- Listen to DOM changes under a given DOM element
- On new image tag added, emit the regular deferred in a stream

The idea is that it could be nice if your lib were able to detect the add/remove of img tags under a given DOM node, so that we could subscribe to the images loading over time.

Maybe it's out of the scope of this library but I think my need is quite common.

I've had to use some code found on SO to do that:
```javascript
// see http://stackoverflow.com/a/14570614/82609
      Wysihtml5SizeMatters.prototype.detectDOMStructureChanges = (function(){
          var MutationObserver = window.MutationObserver || window.WebKitMutationObserver,
              eventListenerSupported = window.addEventListener;

          return function(obj, callback){
              if( MutationObserver ){
                  // define a new observer
                  var obs = new MutationObserver(function(mutations, observer){
                      if( mutations[0].addedNodes.length || mutations[0].removedNodes.length )
                          callback();
                  });
                  // have the observer observe foo for changes in children
                  obs.observe( obj, { childList:true, subtree:true });
              }
              else if( eventListenerSupported ){
                  obj.addEventListener('DOMNodeInserted', callback, false);
                  obj.addEventListener('DOMNodeRemoved', callback, false);
              }
          }
      })();
```

**Comment by desandro** [comment]
Thanks for this feature request! Looks like this issue didn't get much interest over time. Closing!
