### ISSUE TITLE
Please add this to nuget

### ISSUE THREAD

**Issue by sammyfa** [desandro/imagesloaded#138]
**Would be really great to have this as a nuget package** (on [nuget.org](http://nuget.org)). It is the package manager for ASP.NET (bower and friends are not supported on .NET).

Preferably with the `jquery.imagesloaded-version.js` and `jquery.imagesloaded-version.min.js` naming convention.

**Comment by desandro** [comment]
Closing this feature request as it didn't get enough interest. :whale:
