### ISSUE TITLE
Bugs appending new elements (Infinite scroll + Masonry / Isotope)

### ISSUE THREAD

**Issue by desandro** [desandro/imagesloaded#14]
Several users have had problems with past versions of imagesLoaded (pre v1.1.0) and Infinite Scroll with Masonry or Isotope. If you're having trouble as well with these, please speak up.

This issue tracker will collect the previous issues held in Masonry and Isotope.

**Comment by lkwrmwtr** [comment]
Hi, still can't seem to make it work on my end. The code that I'm using is:

$( function() {

	var $container = $('.posts-padd');
	
	$container.isotope({
		itemSelector : '.item-wrapper',
		layoutMode: 'masonry'
	});

	$container.infinitescroll({
		navSelector  : '.pagination-padd',
		nextSelector : '.pagination-padd a:last-child',
		itemSelector : '.item-wrapper',
		loading: {
			finishedMsg: 'No more pages to load.',
			img: 'http://i.imgur.com/qkKy8.gif'
		}
	},
		function( newElements ) {
			var $newElems = $( newElements ).css({ opacity: 0 });
			$newElems.imagesLoaded(function(){
				$newElems.animate({ opacity: 1 });
				container.isotope( 'appended', $newElems, true ); 
			});
		}
	);
	
});

**Comment by seta-donhh6551** [comment]
Hello, Please help.

I using istope for my website. When window scroll ajax load more items. But items is overlap. Where is incorrect in my code. 
This is url for my website : http://vietpranks.com/

Sorry for my english. Thanks all very much

**Comment by seta-donhh6551** [comment]
Who can help me, Please :)

**Comment by harpreetsb** [comment]
If you are using ajax to call new results with infinite scroll, you would
require to reload the masonry or do a refresh on masonry. everytime you
fetch content.

**Comment by seta-donhh6551** [comment]
in jquery when ajax loaded complete, we can using .On to run event live which not load js function again. we can using istope like this?

We can using like this?

$(obj).on.istope(function(){});

If it's not work, how will load istope?
I try with 

success: function (result) // ajax loaded completed
            {
				var $demo = $('.page-main');
                                 abc = $(result);
				$demo.find('.grid-portfolio').imagesLoaded(function () {
					$demo.find('.grid-portfolio').append( abc ).isotope( 'appended', abc );
				});
            }

But items is overlap. Plase for me a solution.

Thanks all, sr for my english

**Comment by JWiersema** [comment]
I have a problem with an implementation where I'm loading more content. When the content for the second page has been loaded and is appended the whole grid moves down to exactly after where the original content was. The following content (is part of) the code that is run each time a new page has been fetched. This cannot be done with a callback like in the inifinite scroll code.

      if (typeof g_Isotopegrid === 'undefined') {                        
                        g_Isotopegrid = $('.grid').isotope({
                            itemSelector: '.grid-item',
                            stamp: '.stamp',
                            masonry: {
                                columnWidth: 255,
                                gutter: 30
                            }
                        });                                                              
                    }

                  // Append all the hidden items to the visible items element
                  hiddenElm.children().each(function () {

                    // Append the items to the visible div
                    $(this).appendTo(visibleElm);
                    
                    // only append new items
                    g_Isotopegrid.isotope('appended', $(this));                                       
                  });
                    
                    // re-layout after images are loaded
                    $('.grid').imagesLoaded(function() {
                            g_Isotopegrid.isotope('layout');
                    });

Does anyone have any suggestions as to why the re-layout is working but it moves the whole grid down till after where the content of the first load was?

**Comment by Paul-Allen** [comment]
Guys, I have Infinite Scroll and Isotope working on WordPress almost perfectly.

I have six items loading initially, then the next 6 load in on scroll, this works perfectly until, I click on one of the filter categories, then scroll down, the correct category items load in perfectly, but the other category items load up above the first item, then  disappear. They kind of flash on and off.

Has anyone experienced this?

I've set up a demo here http://test.wpdev.click/

Click on the Logos filter, then scroll down and you will see items flash above the top left item.

Any help/guidance would be greatly appreciated!

Thanks in advance.

**Comment by ma3ie4** [comment]
Hi,
this solution works for me (infinite scroll + isotope) :

```
// Used scripts:
// http://isotope.metafizzy.co/
// http://imagesloaded.desandro.com/
// https://github.com/infinite-scroll/infinite-scroll

if ($('.js-init-isotope').length > 0) {
    var $gridIsotope = $('.js-init-isotope').isotope({
        layoutMode: 'fitRows'
    });

    $gridIsotope.imagesLoaded().progress(function() {
        $gridIsotope.isotope('layout');
    });


    $('.js-infinite-scroll').infinitescroll({
        loading: {
            finished: undefined,
            finishedMsg: '<div class="alert">Finish loading</div>',
            img: '/images/reload.svg',
            msg: null,
            msgText: "",
            selector: '.items-list',
            speed: 'fast',
            start: undefined
        },
        state: {
            isDuringAjax: false,
            isInvalidPage: false,
            isDestroyed: false,
            isDone: false,
            isPaused: false,
            currPage: 1
        },
        behavior: undefined,
        binder: $(window),
        nextSelector: ".nav-previous > a",
        navSelector: ".pagination",
        contentSelector: '.items-list > .inner',
        extraScrollPx: 150,
        itemSelector: ".post",
        animate: false,
        pathParse: undefined,
        dataType: 'html',
        appendCallback: true,
        bufferPx: 40,
        errorCallback: function() {

        },
        infid: 0,
        pixelsFromNavToBottom: undefined,
        path: undefined,
        maxPage: undefined
    }, function(newElements) {
        // append new elements
        // http://isotope.metafizzy.co/methods.html
        $gridIsotope.isotope()
            .append(newElements)
            .isotope('appended', newElements);

        // trigger the isotope layout after all images are loaded
        // http://imagesloaded.desandro.com/#jquery
        $gridIsotope.imagesLoaded().always(function() {
            $gridIsotope.isotope('layout');
        });

    });
}
```

**Comment by juliusbangert** [comment]
Please could you advise me how to, (or show me an example code block of) using isotope with infinite scroll together on a wordpress custom-post-type archive page. It seems everything in this thread is for the older version of both scripts. So far I have my php WP_Query generating ten posts per page and am trying this js...

`var $grid = $('.grid').isotope({
	itemSelector : '.grid-item',
	columnWidth : '.grid-sizer',
	percentPosition : true
});
		
var iso = $grid.data('isotope');
		
$grid.infiniteScroll({
	hideNav: '.pagination',
	path : '.pagination #next_archive_page',
	append : '.grid .grid-item',
	outlayer : iso,
	scrollThresold: 200
});`

Using the infiniteScroll event callbacks and console log, I can see that _request_, _load_ and _append_ are being fired but I don't see anything happening in the page. Any suggestions?

**Comment by desandro** [comment]
@juliusbangert Your JS looks good. If you can provide a live link to your issue I may be able to take a look. Can you please open a new issue in the [Infinite Scroll tracker](https://github.com/metafizzy/infinite-scroll/issues/)?

---

I opened this issue back in 2012. All the libraries involved have had major updates. Please look at opening new issue in [Infinite Scroll tracker](https://github.com/metafizzy/infinite-scroll/issues/).
