### ISSUE TITLE
Get HTTP status code for broken (or non-broken!) images

### ISSUE THREAD

**Issue by arxpoetica** [desandro/imagesloaded#146]
Searched through the library (I'm using it—thanks, it's awesome), but I can't seem to find a way to get at the http status code for broken (or non-broken!) images.

I believe this is available through the onComplete listener:

```
...
onComplete: function() { console.log(this.status); /* "404" for example */ }
...
```
Do you have any idea how I could get the status? Thanks.

(Been looking at XHR stuff like this: http://stackoverflow.com/a/3915698/209803 — if that helps at all. :P )

**Comment by desandro** [comment]
I'm closing this feature request as it didn't get enough public interest

**Comment by qikkeronline** [comment]
I'd also like to see this happening, my case is for instance a YouTube cover image that doesnt exist.
Youtube returns a functioning image (and imagesloaded correctly reports its been loaded) but the requests also returns a 404 and an image that makes my application ugly.
E.g. [https://i1.ytimg.com/vi/tZeMMyHKPY0/maxresdefault.jpg](https://i1.ytimg.com/vi/tZeMMyHKPY0/maxresdefault.jpg)
