### ISSUE TITLE
Object doesnt support this property or method error in IE8

### ISSUE THREAD

**Issue by sivaprasad9394** [desandro/imagesloaded#149]
Hi,

I am getting the below error,Object doesn't support this property or method in IE8.
I am using jquery version "1.7.1".
After my ajax request call , all the images loaded in the screen i am calling some external function...Please refer the image... I cant upload the image....
Thanks
request.done(function(data,status) {
if (data !== undefined) {
jQuery("div#velocity_content").empty().append(data.html);
jQuery(window).trigger("ReloadSomDataEvent");
if(isPortalEnv){
if (jQuery('#velocity_content') != null){ 
      var $container = jQuery('#velocity_content'); 

   // Here i am getting error,i cant upload image so added code here.......
       $container.imagesLoaded( function(){
         jQuery(window).trigger("forceResize");
         window.parent.parent.scrollTo(0,0);
});

}

**Comment by lilyjiang** [comment]
I have the same error with jQuery 1.8.2.

**Comment by desandro** [comment]
Can you put together a reduced test case that demonstrates this issue? Try forking this CodePen: http://codepen.io/desandro/pen/yyNeMY
