### ISSUE TITLE
Get Image id when 'Visit website' button is clicked

### ISSUE THREAD

**Issue by SamAhb** [desandro/imagesloaded#179]
Hi, I'm trying to get the id of the image when the link button is clicked so that an ActionResult can recive the value, but I can't find where to get this value...

Any advice is appreciated...

Thanks in advance.. 

![captura](https://cloud.githubusercontent.com/assets/11050188/6236389/498b1f70-b69f-11e4-81e6-e4015d2a6763.JPG)

**Comment by desandro** [comment]
hi there! Sorry, but I do not think this is related to imagesLoaded. I'll have to close this issue.
