### ISSUE TITLE
callback arguments

### ISSUE THREAD

**Issue by yairEO** [desandro/imagesloaded#181]
please specify in the README what are the arguments being returned to the callback function.

https://github.com/desandro/imagesloaded/blob/master/README.md

**Comment by desandro** [comment]
Callback arguments are documented under [Events](http://imagesloaded.desandro.com/#events). Is there something in particular you are looking for?

**Comment by yairEO** [comment]
it is not obvious at all that the same parameters as the events are also in the callback.
I would suggest to re-write it like so:

    // selector string
    imagesLoaded( '#container', function(instance) {...});

But, this is also extremely weird that the `this` scope is the exact same as the `instance` parameter, which makes the parameter redundant. Nowhere in the README does the scope of the callback function is mentioned btw.

**Comment by desandro** [comment]
I'm not a fan of the callback pattern as it isn't clear _when_ the callback is supposed to be triggered to the developer. Use Events instead.
