### ISSUE TITLE
Unable to get value of the property 'bind' in IE9

### ISSUE THREAD

**Issue by joseluisq** [desandro/imagesloaded#183]
I have this bug in **IE9**:

```sh
SCRIPT5007: Unable to get value of the property 'bind': the object is null or undefined 
imagesloaded.js, line 291 char 5`
```

In my js file:

```js
window.imagesLoaded(document.body, function(){});
```

I think that bug is related to **eventie** binding helper.
Any idea?

**Comment by desandro** [comment]
Can you check that `document.body` exists? It's possible that this code is occuring in the `head` of the document and that `document.body` has not been mapped yet. Using `document.querySelector('body')` may work instead

**Comment by joseluisq** [comment]
Code is placed in the end of `body` tag, so I tried this:

```js
var $body = document.querySelector('body');
console.log($body);
// [object HTMLBodyElement]

window.imagesLoaded($body, function(){});
```
I see that body reference exists

**Comment by desandro** [comment]
I was not able to reproduce this error. Can you provide a reduced test case. Try forking http://codepen.io/desandro/pen/zxaOVX

![screen shot 2015-02-25 at 5 21 49 pm](https://cloud.githubusercontent.com/assets/85566/6381935/e1d654f6-bd12-11e4-8fbf-31c87e50703e.png)

**Comment by joseluisq** [comment]
Hi @desandro 
I forked your code and now works fine:

![image](https://cloud.githubusercontent.com/assets/1700322/6394581/700ebfb4-bda0-11e4-8bf2-394965ba9425.png)

I used the imageloaded uncompressed version via bower:

```html
<script src="bower_components/eventEmitter/EventEmitter.js"></script>
<script src="bower_components/imagesloaded/imagesloaded.js"></script>
```

I forget to add the `eventie` helper:

```html
<script src="bower_components/eventEmitter/EventEmitter.js"></script>
<script src="bower_components/eventie/eventie.js"></script>
<script src="bower_components/imagesloaded/imagesloaded.js"></script>
```

Apparently, In Chrome, Firefox and latest versions for IE this works fine (without `eventie` helper)
I think that is because I have (before included) the latest jQuery version and so this supports [bind](http://api.jquery.com/bind/) envent handler (can you confirm this?) for this I couldn't to see the error, in my case in latest versions of IE.

Thanks for your support and I'll be tuned for new changes.
Regards
