### ISSUE TITLE
Getting `Uncaught TypeError: Cannot read property 'length' of null`

### ISSUE THREAD

**Issue by mrzool** [desandro/imagesloaded#184]
At `imagesloaded.pkgd.js:627`.

The callback is not firing at all. Any idea what might be causing this?

**Comment by desandro** [comment]
Can you provide a **reduced test case**? Here's a CodePen you can fork:  http://codepen.io/desandro/pen/zxaOVX

**Comment by mrzool** [comment]
I figured it out after seeing all was working on CodePen. I was simply calling my script to early. Putting it before the closing `</body>` tag solved the issue.

Thanks!
