### ISSUE TITLE
Add imagesloaded.min.js for automatic CDN updates

### ISSUE THREAD

**Issue by hubdotcom** [desandro/imagesloaded#187]
Have submitted a PR for automatic update of the package on jsdelivr - https://github.com/jsdelivr/jsdelivr/pull/4295

This will keep project files up to date
https://github.com/jsdelivr/jsdelivr/tree/master/files/imagesloaded

A imagesloaded.min.js file is required to maintain backwards compatibility for those using the 'latest' branch:
http://cdn.jsdelivr.net/imagesloaded/latest/imagesloaded.min.js

**Comment by hubdotcom** [comment]
Update, this is now accepted and the CDN bot is pulling updates of imagesloaded, unfortunately without the imagesloaded.min.js this is failing:
https://github.com/jsdelivr/jsdelivr/pull/4296

Please add this file so we can get the latest version in the CDN. Thanks!

**Comment by desandro** [comment]
The repo already includes `imagesloaded.pkgd.min.js`. I'd rather not include two of the same file.

**Comment by hubdotcom** [comment]
Ahh I see, would this be identical? I'll put in a request with jsDelivr to see if they will make an exemption

**Comment by desandro** [comment]
Perhaps not. If `imagesloaded.min.js` is a minified version of `imagesloaded.js`, then it would be different. But I'd rather not include this kind of file. I see minified files as being useful for people that just want to add it to a `<script>`. `imagesloaded.min.js` would not be useful in that case.

**Comment by hubdotcom** [comment]
No problem, let's see what we can do
