### ISSUE TITLE
 TypeError: undefined is not a function - imagesLoaded ?

### ISSUE THREAD

**Issue by RevConcept** [desandro/imagesloaded#189]
Not sure what the issue is - had some elements overlapping so I tried using imagesLoaded and I'm getting this error in console:

 TypeError: undefined is not a function (line:95)

Here is my JS:

    $( function() {
      
      var $container = $('.isotope').isotope({
        itemSelector: '.episode',
        masonry: {
          columnWidth: 250,
          gutter: 20,
          isFitWidth: true
        }
      });

      $container.imagesLoaded( function() {
        $container.isotope('layout');
      });

    });

Also, here is our staging site where the error is showing: http://dftg.revelationconcept.com/journey/

**Comment by desandro** [comment]
Looks like you need to add [imagesloaded.pkgd.js](http://imagesloaded.desandro.com/imagesloaded.pkgd.js) to your page.

**Comment by RevConcept** [comment]
Oh, wow. So sorry! I thought that was a part of the isotope library...I didn't see it was something separate in the documentation...thanks!
