### ISSUE TITLE
When cloudflare service added to DNS, images are loading, but html overlay is not disappearing

### ISSUE THREAD

**Issue by nikhiljohn10** [desandro/imagesloaded#193]
I have enabled CloudFlare DNS Service in my new site. But when i used the imagesloaded to preload images, the html overlay is not disappearing. When i inspected the html, i found cloudflare injected some js file in to my html file before css or js file loads.

**Comment by desandro** [comment]
Thanks for reporting this issue. Do you have a live URL we could take a look at?

**Comment by nikhiljohn10** [comment]
The conflict is really between Rocket loader of cloudflare. When I turn that off, everything went back to normal. But still Rocket Loader is a killer of "imagesloaded" module. I don't know if this is fixable. Anyway, you can close this issue or you can reproduce the issue as follows.

Steps:

1. Host a site that use imageloaded for loading images.
2. Make a account at cloudflare service.
3. Move the DNS details of the site to Cloudflare.
4. Turn off "Rocket Loader" feature of cloudflare.
5. Browser the site after cloudflare is activated completely.
6. Now the imageloaded displays its loading gif. But it will not disappear even after the full site is loaded.

**Comment by cravecode** [comment]
I just wanted to chime in to add that this is a legitimate issue. For anyone else interested, currently your only option is to disable CloudFlare's Rocket feature. I've tried adding `data-cfasync="false"` to the imagesloaded `script` tag as this [article suggests](https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-) with no luck.

**Comment by cravecode** [comment]
For a simple catchall, it may be a good idea to add a hard set timeout to hide the overlay.
