### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by MentalGear** [desandro/imagesloaded#194]
Please add an easy to spot section that describes the browser support of your plugin.
Almost went nuts trying to find it, and it should be a standard for all js plugins.

And i'm not the only one who thinks that:
http://stackoverflow.com/questions/26732085/imagesloaded-javascript-library-what-is-the-browser-device-support

I mean, what's the reason for not showing the browser support .. unless you aren't sure about it yourself?

**Comment by desandro** [comment]
Added [Browser support](http://imagesloaded.desandro.com/#browser-support) to the site.
