### ISSUE TITLE
How to say "when first, second, and third images of # images are loaded..."

### ISSUE THREAD

**Issue by jan1980** [desandro/imagesloaded#198]
I'd like to make a conditional so imagesloaded activates some code when the 1st, 2nd and 3rd images of many images (let's say, 50) are loaded.

(in my particular case, fade in a carousel with heavy images)

How could I achieve something like that?

Thanks,

**Comment by desandro** [comment]
You'll want to use the `progress` event. [The main demo uses progress to update the `progress` element](http://codepen.io/desandro/pen/yyNeMY).

``` js
// jQuery
var imgLoadCount = 0;
$('selector').imagesLoaded().progress( function( instance, image ) {
  // update count
  imgLoadCount += image.loaded ? 1 : 0;
  if ( imgLoadCound == 1 ) {
    // do something when 1st image loads
  } else if ( imgLoadCount == 2 ) {
    // do something when 2nd image loads
  } else  {
    // more stuff
  }
});
```
