### ISSUE TITLE
When used with Qtip2, creates problems with qtip positioning

### ISSUE THREAD

**Issue by spacelady00** [desandro/imagesloaded#199]
When I include the imagesloaded.pkgd.js script, my tooltips created with Qtip2 no longer position correctly, even when I don't call imagesLoaded at all in my code and just include the script.

Any ideas on how to fix this?

**Comment by desandro** [comment]
Sorry to hear you're having trouble with imagesLoaded. If you can produce a **reduced test case** I can better understand the problem [Try forking this CodePen](http://codepen.io/desandro/pen/yyNeMY)

**Comment by spacelady00** [comment]
I've done a simple test case, but the positioning error only happens [in the CodePen](http://codepen.io/anon/pen/vOPYJo) the first time the tooltip is created

**Comment by desandro** [comment]
Sorry, but I will not be able to debug this issue.
