### ISSUE TITLE
Missing eventEmitter with Webpack

### ISSUE THREAD

**Issue by opportunato** [desandro/imagesloaded#203]
Hey!

I've been getting an error while using imagesloaded with webpack while requiring it, and the trouble looks to be in the module definition. The error is:

`Module not found: Error: Cannot resolve module 'eventEmitter/EventEmitter' in /Users/opportunato/projects/grabr-web-client/node_modules/imagesloaded`

And the related code is:

```javascript
if ( typeof define === 'function' && define.amd ) {
    // AMD
    define( [
      'EventEmitter/EventEmitter',
      'eventie/eventie'
    ], function( EventEmitter, eventie ) {
      return factory( window, EventEmitter, eventie );
    });
  }
```

There is no folder "EventEmitter" in my node_modules/imagesloaded folder, just "wolfy87-eventemitter".
So, if I change `EventEmitter/EventEmitter` to 'wolfy87-eventemitter/EventEmitter' (as defined in package.json), everything works smoothly. Am I missing something here or is there a need in PR?

**Comment by desandro** [comment]
Thanks for reporting this bug. Can you confirm what module loader you are using (Webpack, Browserify, ..?)

**Comment by opportunato** [comment]
Yeah, I am using webpack. Do you need my config?

**Comment by afader** [comment]
Could it be fixed in a similar way to this: https://github.com/desandro/masonry/issues/679

**Comment by mannebusk** [comment]
Can confirm having the same issue with Webpack. Using version 3.1.8 of imagesloaded.

**Comment by desandro** [comment]
I've added docs on Webpack + imagesLoaded http://imagesloaded.desandro.com/#webpack

Try it out and report back if there's still an issue. Sounds like there still might be an issue with adding the alias.

**Comment by daphnesmit** [comment]
Still doesnt work..

**Comment by alexandreaco** [comment]
Thanks, @mannebusk. That worked for me too!

**Comment by desandro** [comment]
[imagesLoaded v4.1.0](https://github.com/desandro/imagesloaded/releases/tag/v4.1.0) switched from `eventEmitter` to `ev-emitter`. As `ev-emitter` has the same registered name in bower npm and Bower registries, this Webpack bug will no longer occur.

The `config` hacks are no longer necessary. You can `require('imagesloaded')` no problem.

Closing as fixed :tada:

**Comment by michalmikolajczyk** [comment]
@mannebusk your solution also helps with Flickity, thanks!
