### ISSUE TITLE
imagesLoaded + Masonry when there are no images

### ISSUE THREAD

**Issue by lachlanjc** [desandro/imagesloaded#207]
I'm using Masonry for a new project, and it's been awesome. The loading images were messing with the layout, so I added imagesLoaded (with `progress()`). However, occasionally the grid will load contents that have no images, and so Masonry never lays out the grid because images were never done loading. I could use a jQuery selector to check if there are no images, but that feels a bit heavy. What's the best way to still run Masonry even if there are no images to load?

**Comment by desandro** [comment]
imagesLoaded() still triggers `always` with 0 images. Checking for images before using imagesLoaded might be the best solution.

**Comment by lachlanjc** [comment]
Thanks @desandro! Checking for images first now and everything's working brilliantly. 🙌
