### ISSUE TITLE
imagesloaded only works once

### ISSUE THREAD

**Issue by Dans-Creative** [desandro/imagesloaded#209]
I have a problem with imagesloaded and the jquery .load() function.
I made a portfolio side for me, where the projects are opend with .load(). The problem with load was, that it loaded the html file too soon and the images weren't loaded jet. So I used imagesloaded, which works fine, but only once.
When i close a project the #works-content-wrapper will be emptyed, so I can load a new project in this container. If I click on a new project, than it's like the imagesloaded plugin doesn`t exists. It loads the html file too soon and the loading of the images can be seen.

Here is my website:
http://dans-creative.de/test/index.html
Just open a project and there will be a preloader. Than close the project and open another one. It will open instantly, without any preloader.

```
$(".project").click(function(){
        $("#works-wrapper").css("z-index", "2");
        $("#works-wrapper").css("opacity", "1");
        $("#works-preloader").css("opacity", "1");

        var projectlink = $(this).attr("href");

        $("#works-content-wrapper").load(projectlink, function() {

            $("#works-content-wrapper").imagesLoaded( function() {
                projectwindowopen = true;
                $("#works-content-wrapper").css("opacity", "1")
                $(".works-body").css("height", scrollwrapperheight + 20);
                if(!mobileuse){$(".works-body > div:nth-child(1)").css("height", $(".works-body > div:nth-child(2) img").height() + 30)};
                return false;
            });

            $("#works-close").click(function(){
                projectwindowopen = false;
                $("#works-wrapper").css("opacity", "0");
                setTimeout(function() {
                    $("#works-content-wrapper").empty();
                    $("#works-wrapper").css("z-index", "-1");
                }, 500);
            });
        });
    });
```

**Comment by desandro** [comment]
Sorry to hear your are having trouble with imagesLoaded. This looks like an implementation bug. Sorry, but I won't be able to personally debug this.
