### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by voltmn** [desandro/imagesloaded#212]
And what about SVG images?

**Comment by desandro** [comment]
**Add a 👍  reaction** to this issue if you would like to see this imagesLoaded add support for `<svg>`, including images within SVG. Do not add +1 comments — [They will be deleted](https://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by desandro** [comment]
Closing as a duplicate of #277. Add a 👍 there!
