### ISSUE TITLE
3.2.0 uses a once-method, throws error

### ISSUE THREAD

**Issue by jschill** [desandro/imagesloaded#213]
I tried upgrading to 3.2.0 today and noticed you've changed from .one to .once

```javascript
loadingImage.once( 'progress', onProgress );
```
Is this a dependancy?
If not... "Uncaught TypeError: loadingImage.once is not a function"

Cheers!

**Comment by jschill** [comment]
Brainfreeze. Completely missed the 
```
  "dependencies": {
    "eventEmitter": ">=4.2 <5.0",
    "eventie": "~1.0.4"
  },
```

Sorry! Have a nice weekend!

**Comment by desandro** [comment]
Thanks for reporting this issue.
