### ISSUE TITLE
Electron support

### ISSUE THREAD

**Issue by renataogarcia** [desandro/imagesloaded#215]
Is it possible to run it inside [electron](https://github.com/atom/electron)?

I've tried and I'm getting the following error:
```
Uncaught Error: Cannot find module 'wolfy87-eventemitter'
```

**Comment by desandro** [comment]
Sounds like this is an issue with Electron's package management and imagesLoaded is currently set up. Could you look into what format Electron uses — CommonJS, AMD, etc?

**Comment by renataogarcia** [comment]
I believe it is CommonsJS. However, I'm using imagesloaded in a script running inside a BrowserWindow, so it's not electron/node code.

I can get it working by commenting the following lines seems:
```
} else if ( typeof module == 'object' && module.exports ) {
    // CommonJS
    module.exports = factory(
      window,
      require('wolfy87-eventemitter'),
      require('eventie')
    );
```
and 
```
else if (typeof module === 'object' && module.exports){
	module.exports = EventEmitter;
}
```

**Comment by desandro** [comment]
It sounds like you are using `imagesloaded.pkgd.js`, when Electron works better using source files. Install imagesloaded via npm and you'll have the `wolfy87-eventemitter` package installed as well

``` bash
npm install imagesloaded
```

**Comment by renataogarcia** [comment]
I tried installing it and using require() previously and I got the module not found error when trying to load it in the renderer process.
I've managed to get it working now. According to my findings in summary you have two options:
- Load imagesloaded via a script tag and set "node-integration": false on BrowserWindow which will remove the modules so it will behave just like it does in a standalone browser, however you can't use other modules such as "ipc".
- Use CommonJS modules by installing and requiring it. When using this approach, if you load an URL using http protocol instead of file, the lookup paths won't contain the node_modules folder; so it will not find the module. In order for this to work you have to manually add the path to the global lookup paths. In my case I've used the following in the renderer process:
```
require('module').globalPaths.push(process.cwd() + '/node_modules');
var imagesloaded = require('imagesloaded');
```
The following issues have more details and helped me figure out the solutions: https://github.com/atom/electron/issues/254 and https://github.com/atom/electron/issues/11

Thanks for looking into it!

**Comment by kinsleykajiva** [comment]
Hi, this  is what i did to make my error go away in electron 
```
`<script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>
 <script type="text/javascript" src="../public/js/frameworks/jquery.js"></script>
  ` <script type="text/javascript" src="../public/js/frameworks/jquery.min.js"></script>
     <script type="text/javascript" src="jquery-ui.min.js"></script>
   <script type="text/javascript" src="../public/js/frameworks/bootstrap.min.js"></script>

    <!-- plugins -->
    <script src="../public/js/frameworks/imagesloaded.pkgd.min.js"></script>
    <script src="../public/js/frameworks/masonry.pkgd.min.js"></script>
     <script src="../public/js/frameworks/holder.min.js"></script>
    <script src="../public/js/frameworks/moment.min.js"></script>
   <script src="../public/js/frameworks/jquery.nicescroll.js"></script>
 

    <!-- custom -->
    <script src="../public/js/frameworks/main.js"></script>
    
    <!-- end: Javascript -->
    <script>if (window.module) module = window.module;</script>
````
