### ISSUE TITLE
ImagesLoad after Resize and in hidden Div (accordion) dosnt sort anymore

### ISSUE THREAD

**Issue by derSteffen** [desandro/imagesloaded#216]
Hello,

I have an accordion-script ... in this there are tabs and in this tabs are masonry-galleries!
The images of the gallery will be load by lazyload.
Everything is fine .. but If i resize the window (with closed accordion) and open the accordions and the tabs which the images was also shown (imageslaod) the images are unsort and there dont sort ... If I resize a second time the the images are sort .. but only on the open accordion / tab!

This Problem is only by loaded images ... galleris with not loaded images are sort after resize and open an accordion. If an accordion open and the images loaded and then resize .. its also okay by an open accordion.

Have anybody an soltion or a tip? Should I destroy every masonry on this page after resize or can I reset the loaded images.

Thank you very much!

Greetings

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with imagesLoaded. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/imagesloaded/blob/master/contributing.md#submitting-issues).
