### ISSUE TITLE
reset() function

### ISSUE THREAD

**Issue by andrisi** [desandro/imagesloaded#223]
Works fine on the first load of a page, but if I load additional images when the user pages through a result list, those images are not reported. A reset() function would be nice, so I could ask your code to report on images being downloaded again. Or shall I call imagesLoaded() on the container element over and over again? This works, but might be problematic. If not, please note this in the readme. Thanks.

**Comment by desandro** [comment]
>  Or shall I call imagesLoaded() on the container element over and over again?

Yes, imagesLoaded checks for images currently in the DOM. When you add new images, you should trigger imagesLoaded again.

**Comment by andrisi** [comment]
Thanks.
