### ISSUE TITLE
Is ev-emitter.js a dependcy for imagesloaded?

### ISSUE THREAD

**Issue by smohadjer** [desandro/imagesloaded#231]
I get an error in browser console (EvEmitter is undefined) if I don't load ev-emitter.js in my page. It seems this is a dependency for using imagesloaded, but the readme doesn't say so, so just wondering. Also is there a way to use imagesloaded without ev-emitter.js? I prefer to have as few dependencies in my script as possible.

**Comment by desandro** [comment]
You can use [imagesloaded.pkgd.js](http://imagesloaded.desandro.com/imagesloaded.pkgd.js) or [imagesloaded.pkgd.min.js](http://imagesloaded.desandro.com/imagesloaded.pkgd.min.js), which includes dependencies

**Comment by smohadjer** [comment]
Thanks. For some reason that had not fixed the error before, but I don't see error anymore.
