### ISSUE TITLE
module.js:339 Uncaught Error: Cannot find module 'ev-emitter'

### ISSUE THREAD

**Issue by heaversm** [desandro/imagesloaded#233]
Hi - I have a web site which successfully uses imagesloaded to detect image load (thanks!) - I am now trying to use electron (a node app) to bundle the site into an application. Because it is a node app, it seems when using `define` in a library (as imagesloaded does), I need to use require to make sure that those defined references are available. For example, in order to use jQuery, I had to switch from:

```
<script src="js/lib/jquery.js">
```
to 

```
<script>
    $ = jQuery = require('./js/lib/jquery-2.2.1.min.js');
</script>
```

But if I try to do this with images loaded:

```
<script>
    imagesloaded = require('./js/lib/imagesloaded.js');
</script>
```

I still get an error with ev-emitter, which seems to originate here:

```
( function( window, factory ) { 'use strict';
  // universal module definition

  /*global define: false, module: false, require: false */

  if ( typeof define == 'function' && define.amd ) {
    // AMD
    define( [
      'ev-emitter/ev-emitter'
    ], function( EvEmitter ) {
      return factory( window, EvEmitter );
    });
  } else if ( typeof module == 'object' && module.exports ) {
    // CommonJS
    module.exports = factory(
      window,
      require('ev-emitter')
    );
  } else {
    // browser global
    window.imagesLoaded = factory(
      window,
      window.EvEmitter
    );
  }

})
```

Do you know how I can include images loaded so that it doesn't throw errors when requiring the ev-emitter?

**Comment by desandro** [comment]
Have you tried requiring [imagesloaded.pkgd.js](http://imagesloaded.desandro.com/#download) instead?

**Comment by heaversm** [comment]
Yes - the error occurs when including any of the three versions of imagesloaded (pkgd,min,or just imagesloaded.js). Is there maybe a way to use require to reference the ev-emitter?

**Comment by desandro** [comment]
Hmm, sounds like the included `ev-emitter` in imagesloaded.pkgd.js is not able to be required.

In that case, you'll have to require it as another library. If you install imagesloaded via npm, it will be installed.

``` bash
npm install imagesloaded
```

You'll then have to resolve the dependency. Either with a config so that `ev-emitter` points to the right place. Or by manually changing `ev-emitter` path to where it needs to be, like `.js/lib/ev-emitter`.

**Comment by heaversm** [comment]
Gotcha - will give it a shot. Thanks for the plugin btw - I've used it on many, many projects.
