### ISSUE TITLE
Is there any destroy() method ?

### ISSUE THREAD

**Issue by waskito** [desandro/imagesloaded#235]
I am using `ReactJS` with `masonry + imagesLoaded` and I have got an error 

```
masonry not initialized. Cannot call methods, i.e. $().masonry("layout")
```
from this code:

```
    var imgLoaded = imagesLoaded(node)
    imgLoaded.on('progress', function(instance){
        $(node).masonry('layout');
    });
```
I have read this http://masonry.desandro.com/faq.html#error-cannot-call-methods-on-masonry-prior-to-initialization-attempted-to-call-___ but I think it's not suited in my situation.
I have multiple page with `masonry + imagesLoaded`, the error is occured when `imagesLoaded` still in progress and I change page.
When I change the page, I `destroy` the `masonry` (I destroy in react's method `componentWillUnmount()`). but `imagesLoaded` is still in progress so it will call `        $(node).masonry('layout');` whether the node is already destroyed or not.

Is there any `destroy()` method in `imagesLoaded` so I can destroy both `masonry` and `imagesLoaded` when the node is unmounted?

Thank you! 😃

**Comment by desandro** [comment]
Thanks for reporting this issue. Sorry, there is no destroy or abort method. See #100 for that feature request.

Could you solve this just by checking state?

``` js
var imgLoaded = imagesLoaded(node)
var isMounted = true;
imgLoaded.on('progress', function(instance){
    if ( isMounted ) {
        $(node).masonry('layout');
    }
});
// isMounted could be set false elsewhere
```

**Comment by waskito** [comment]
Ah got it, it works without errors now! Thanks a lot @desandro !
