### ISSUE TITLE
IE11 image stops loading

### ISSUE THREAD

**Issue by cdwebdev** [desandro/imagesloaded#236]
Hi, I am still seeing an issue where when you reload a page a number of times that is using lazy load, it eventually aborts loading the image on the page. 
A similar problem was reported here but no fix was given: https://github.com/desandro/imagesloaded/issues/40

Was this issue ever resolved? Is there a fix for it?

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you please provide a **reduced test case**? See [submitting issues guidelines](https://github.com/desandro/imagesloaded/blob/master/contributing.md#submitting-issues)
