### ISSUE TITLE
imagesLoaded not working right with Masonry/Materialize?

### ISSUE THREAD

**Issue by kingIZZZY** [desandro/imagesloaded#239]
http://dev.randompod.com

I'm trying to use Materialize with Masonry as templated/exemplified here: https://github.com/Dogfalo/materialize/tree/master/templates/masonry-template.

Grid item positions are still not updating correctly after images are (supposedly) loaded.

Am I using it / doing something wrong?

**Comment by desandro** [comment]
Closing here. Please submit a new issue with Masonry
