### ISSUE TITLE
Cannot resolve module 'imagesLoaded'

### ISSUE THREAD

**Issue by gearmobile** [desandro/imagesloaded#240]
Perhaps in the plugin description in the section about Webpack is the error?

Originally installed the plugin via npm:

```bash
npm install imagesloaded
```
then hooked into webpack:

```javascript
'use strict';
...
var imagesload = require('imagesLoaded');
```

In the console, get connection error plugin:

```bash
./markup/static/js/main.js
Module not found: Error: Cannot resolve module 'imagesLoaded' in /home/zencoder/Projects/stage/ef/markup/static/js
```

But when I change the connection string in webpack on the next line:

```javascript
'use strict';
...
var imagesload = require('imagesloaded');
```

Webpack fulfills without errors, and includes a plugin to build the project:

```bash
Hash: 26472ce9ac9cf164a7b1
Version: webpack 1.13.1
Time: 1774ms
  Asset     Size  Chunks             Chunk Names
main.js  2.43 MB       0  [emitted]  main
chunk    {0} main.js (main) 876 kB [rendered]
    [0] ./markup/static/js/main.js 11.5 kB {0} [built] [1 warning]
    [1] ./~/chart.js/src/chart.js 1.78 kB {0}
    ...
  [160] ./~/imagesloaded/imagesloaded.js 9.62 kB {0} [built]
```

**Comment by desandro** [comment]
Thanks for reporting this issue. Could you elaborate what you mean by

> But when I change the connection string in webpack on the next line

What did you change?

**Comment by gearmobile** [comment]
`var imagesload = require('imagesLoaded');` to `var imagesload = require('imagesloaded');`
In other words - `**imagesLoaded**` to `**imagesloaded**` ( from **uppercase** to **lowercase** )

**Comment by desandro** [comment]
ah! Thanks for pointing that out. I've fixed this [typo on the site](http://imagesloaded.desandro.com/#webpack).
