### ISSUE TITLE
`window` is `this` in packaged code

### ISSUE THREAD

**Issue by BenChirlin** [desandro/imagesloaded#243]
As seen on [this line](https://github.com/desandro/imagesloaded/blob/master/imagesloaded.pkgd.js#L29) the global `window` object is replaced by `this` in the packaged scripts. After including the packaged script on a local project this throws an error which is resolved by swapping it back out.

Not sure if this is an actual issue or I've misinstalled the library but the swap seems to be working for me so far.

**Comment by desandro** [comment]
Thanks for submitting this issue. I've updated EvEmitter in the pkgd file to v1.0.3 which fixes this issue.
