### ISSUE TITLE
How can I manipulate a variable that exists outside .done(), from within .done()?

### ISSUE THREAD

**Issue by dylanfpaul** [desandro/imagesloaded#244]
I'm sorry if this is the wrong way to seek out an answer for this issue but I figure why not. Basically I have a standard imagesLoaded implementation. I want to know how can I manipulate a pre-existing variable within .done(). So basically something like this:
var p = 0;
.done( function( instance ) {
 //manipulate p variable
}); 

console.log(p);

Thanks.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with imagesLoaded. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/imagesloaded/blob/master/contributing.md#reduced-test-case-required).
