### ISSUE TITLE
jQuery 3.1.1 deprecated bind()

### ISSUE THREAD

**Issue by gregarios** [desandro/imagesloaded#246]
bind() is deprecated in jQuery 3 but their solution of using .on() instead doesn't seem to work here:

`// HACK check async to allow time to bind listeners
  setTimeout( function() {
    this.check();
  }.bind( this ));
}`

**Comment by desandro** [comment]
`bind()` in this context is using [vanilla JS Function.prototype.bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) so we should be all good here.
