### ISSUE TITLE
Can I use imagesloaded to randomize the position of images in the grid?

### ISSUE THREAD

**Issue by etale-cohomology** [desandro/imagesloaded#251]
It'd be nice.

**Comment by desandro** [comment]
Sounds like you're asking a question about Masonry. 

I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
