### ISSUE TITLE
Proposal: add option to skip loading children images

### ISSUE THREAD

**Issue by tdmalone** [desandro/imagesloaded#252]
I have a situation where I want to load a background image on a parent div - and wait for it to load - before I make the page usable. I then lazy load child images as they're needed.

imagesLoaded is trying to detect loading of those child image tags, and is failing because I haven't set the src's of them yet.

I've commented out [lines 255-275](https://github.com/desandro/imagesloaded/blob/master/imagesloaded.pkgd.js#L255-L275) and this is solving the specific issue I'm encountering, so I thought I'd propose adding an `ignoreChildren` or similar option to do the same thing.

**Comment by desandro** [comment]
Thanks for reporting this issue. Have you tried using a child selector ( `background: item` ) so that the other `img` tags aren't being selected?
