### ISSUE TITLE
error the first time I check of images loaded

### ISSUE THREAD

**Issue by medBouzid** [desandro/imagesloaded#256]
I get this error when I try to test for images are loaded
```
TypeError: this.proxyImage.addEventListener is not a function
this.proxyImage.addEventListener( 'load', this );
```
The second time when the images are cached and the request returns "304 Not Modified" the plugin works correctly

**Update :** 

That's weird because this happens only when I load images using ajax and I loop through the result then I append img tags to the container... if there is no ajax, no loop and no adding image dynamically to the container the error doesn't happen

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with imagesLoaded. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/imagesloaded/blob/master/contributing.md).
