### ISSUE TITLE
Urgent -- your CDN's been hacked!

### ISSUE THREAD

**Issue by calex** [desandro/imagesloaded#258]
Using this as a CDN caused a hack MacKeeper download warning to appear on my in-development website before content loaded. 

Clicking on the cdn links you provide on your imagesloaded website takes one to shttps://compliance-jessica.xyz/a.php.

Clicking on the .js files linked to on your site shows some odd-looking code, too.

**Comment by desandro** [comment]
Thanks for reporting this issue. The [bug was with unpkg, which has since been resolved](https://twitter.com/unpkg/status/852669269103869952).
