### ISSUE TITLE
Not working images loaded with little html changes

### ISSUE THREAD

**Issue by BhargavBhandari90** [desandro/imagesloaded#260]
Can you look at here once. http://codepen.io/bhargavbhandari90/pen/BRPQGg/

I made changes on html and changed css according to it. 

I copied from here : http://codepen.io/desandro/pen/RPKgEN  ( Working fine here )

Why it is not working with my structure? Am I missing something?

**Comment by desandro** [comment]
Looks like your images are behind permission 
![screen shot 2017-05-16 at 10 51 32 am](https://cloud.githubusercontent.com/assets/85566/26123301/6a31f95e-3a48-11e7-852f-164fa2ddd41b.png)

**Comment by BhargavBhandari90** [comment]
Thanks @desandro 
for looking into this. I manage to solve the issue. Actually it was not an issue. After exploring some options, it was resolved.

So closing this.
