### ISSUE TITLE
Background image loaded won't work properly

### ISSUE THREAD

**Issue by desirelabs** [desandro/imagesloaded#261]
Hi there, 
I tried implementing imageloaded on background images as explained in the documentation : 
```
let container = document.querySelector('.projects-list');
        imagesLoaded(container, { background: '.project' }, (imgLoaded) => {
          console.log(imgLoaded.isComplete)
          var msnry = new Masonry( container, {
            // options
            itemSelector: '.project',
            gutter: gutter,
            columnWidth: function( containerWidth ) {
              return containerWidth /columns;// depends how many boxes per row
            }(), // () to execute the anonymous function right away and use its result
            isAnimated: true
          })
        })
```
`isComplete` is returned as `true` wheareas background images are stil loading. I may misunderstood the expected behaviour, but it seems it doesn't wait for background images to be fully loaded.
Can you please help me trough this ?
Thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with imagesLoaded. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/imagesloaded/blob/master/contributing.md).
