### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined (imagesloaded.js:115) 

### ISSUE THREAD

**Issue by Firman95** [desandro/imagesloaded#264]
I got that error by running every test provided in the plugins with fresh install.

This is the code where the error comes from.
`ImagesLoaded.prototype = Object.create( EvEmitter.prototype );
`
Any idea why this happens?

**Comment by desandro** [comment]
Sounds like you're using imagesloaded.js, when you'll need the packaged version imagesloaded.pkgd.js

**Comment by Firman95** [comment]
That solved the problem, thanks!

**Comment by rmazarei** [comment]
Thank you @desandro. Solved my problem too.

**Comment by G3-Logic** [comment]
Solved for me as well. So what is the difference between the packaged version and the unpackaged version?

**Comment by desandro** [comment]
> So what is the difference between the packaged version and the unpackaged version?

The packaged version includes the other JS dependencies (currently, only [ev-emitter](https://github.com/metafizzy/ev-emitter)) in the JS file.

The unpackage version does not include this file, as it is included module definition & in the manifest .json and will be added via module loader.

**Comment by liu332906484** [comment]
Uncaught TypeError: Cannot read property 'imagesLoaded' of undefined why??
