### ISSUE TITLE
image in inline svg?

### ISSUE THREAD

**Issue by illycz** [desandro/imagesloaded#271]
Is it possible check this?

**Comment by desandro** [comment]
Currently, no, imagesLoaded does not officially support `<image>` elements within inline `<svg>`.

**Add a 👍  reaction** to this issue if you would like to see this feature added. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by desandro** [comment]
Closing as a duplicate of #277 . Add a 👍 there!
