### ISSUE TITLE
Doesn't work when setting the src

### ISSUE THREAD

**Issue by Gruski** [desandro/imagesloaded#275]
Event triggers on initial <img> render but not if subsequently the src is set multiple times through javascript to new URL. I would expect it to trigger the event every time the src is changed.

**Comment by desandro** [comment]
> I would expect it to trigger the event every time the src is changed.

Sorry! This is not how imagesLoaded was designed to work. You can build your own solution to track that sort of change, listening for `load` or `error` event.

**Comment by Gruski** [comment]
On load is not reliable for cached images and error event is not appropriate if there is no error. That's the whole reason we needed an imagesloaded library to begin with. So neither are a good solution. Hope you can add this ability since the library seems incomplete without it.
