### ISSUE TITLE
Combination with masonry, infinitescroll and gifs

### ISSUE THREAD

**Issue by MrMooky** [desandro/imagesloaded#280]
I'm having some trouble with posted gifs in combination with [imagesloaded](https://github.com/desandro/imagesloaded) and masonry. Basically, this happens quite often:

![screenshot 2019-02-24 at 14 51 03](https://user-images.githubusercontent.com/3603346/53300182-f40d7e00-3843-11e9-99e9-7083337f00f0.png)

![screenshot 2019-02-24 at 14 50 48](https://user-images.githubusercontent.com/3603346/53300186-f8d23200-3843-11e9-9357-b61ff296b500.png)

The initial loading seems to work fine, but as soon as the second or third page loads with [infinite-scroll](https://github.com/metafizzy/infinite-scroll), the gifs are cut off sometimes. How could I prevent this?

How my code looks like:

```
$.getScript("https://webdata.friendships.me/js/infinite-scroll.min.js", function() {
            $.getScript("https://webdata.friendships.me/js/masonry.js", function() {

                $grid = $('.timeline__posts__container .posts').masonry({
                    itemSelector: 'none',
                    columnWidth: '.grid__col-sizer',
                    gutter: '.grid__gutter-sizer',
                    percentPosition: true,
                    stagger: 30,
                    visibleStyle: { transform: 'translateY(0)', opacity: 1 },
                    hiddenStyle: { transform: 'translateY(100px)', opacity: 0 },
                });

                // get Masonry instance
                var msnry = $grid.data('masonry');

                // initial items reveal
                $grid.imagesLoaded( function() {
                    $grid.removeClass('are-images-unloaded');
                    $grid.masonry( 'option', { itemSelector: '.timeline__post' });
                    var $items = $grid.find('.timeline__post');
                    $grid.masonry('appended', $items);
                });

                $grid.infiniteScroll({
                    path: '.nextPage',
                    append: '.single__post',
                    outlayer: msnry,
                    status: '.page-load-status',
                    history: false,
                    hideNav: 'ul.pagination'
                });

            });
        });
```

**Comment by desandro** [comment]
Thanks for reporting this issue. Do you have a live URL I could take a look at?

**Comment by MrMooky** [comment]
You can see it on https://friendships.me. You can login with User and Pass 'desandro'.

**Comment by desandro** [comment]
Thanks for that. I didn't see the overlap in Chrome or Firefox, but I did see it in Safari. In which case, look at metafizzy/infinite-scroll#671 for some related solutions

**Comment by MrMooky** [comment]
Ah, great. I'll check if any workaround mentioned there works. Thanks a lot for checking and your feedback. :)
