### ISSUE TITLE
[QUESTION] Where I can find the CI service? 

### ISSUE THREAD

**Issue by gustavosizilio** [desandro/imagesloaded#284]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by desandro** [comment]
Hello! To your question: no and no. I rely on a lot of static HTML stuff. You can run tests:

```
npm install
bower install
```

Then view test/index.html

**Comment by gustavosizilio** [comment]
Thank you very much!
