### ISSUE TITLE
Background images aren't considered in load

### ISSUE THREAD

**Issue by facultymatt** [desandro/imagesloaded#29]
Not sure if this is a limitation or just hasn't been implemented... but it would be great if background images could be detected along with <img> tags.

**Comment by matthewgovaere** [comment]
+1

**Comment by DonSanto** [comment]
+1

**Comment by homerjam** [comment]
+1

**Comment by ladytellur** [comment]
+1

**Comment by promptdev** [comment]
+1

**Comment by rob-gordon** [comment]
+1

**Comment by nevace** [comment]
+1

**Comment by aryehshai** [comment]
+1

**Comment by desandro** [comment]
:tada: :star: :rainbow:  [imagesLoaded v3.2.0 now supports background images](http://imagesloaded.desandro.com/#background) :rainbow: :star: :tada:  Try it out!

---

Set `{ background: true }` to detect when the element's background image has loaded.

``` js
// jQuery
$('#container').imagesLoaded( { background: true }, function() {
  console.log('#container background image loaded');
});

// vanilla JS
imagesLoaded( '#container', { background: true }, function() {
  console.log('#container background image loaded');
});
```

Set to a selector string like `{ background: '.item' }` to detect when the background images of child elements have loaded.

``` js
// jQuery
$('#container').imagesLoaded( { background: '.item' }, function() {
  console.log('all .item background images loaded');
});

// vanilla JS
imagesLoaded( '#container', { background: '.item' }, function() {
  console.log('all .item background images loaded');
});
```

**Comment by nevace** [comment]
Amazing, thanks!

**Comment by arxpoetica** [comment]
++++AWESOME!!!

**Comment by desandro** [comment]
I'm closing this issue as resolved. If you run into an issue with imagesLoaded and background images, please open a new issue.
