### ISSUE TITLE
Dev Tools - Disable Cache causes resource to load indefinitely (Safari and Chrome)

### ISSUE THREAD

**Issue by willryanuk** [desandro/imagesloaded#292]
When you are using Chrome Dev Tools (latest Chrome 80.0.3987.122 on OS X) with "Disable Cache", it can cause images to download multiple times.

In Safari (13.0.5 (15608.5.11 OS X), it is much worse... the callback handler:
`imagesLoaded(mainProductImage,` mainProductImageLoaded);

is called thousands of time (actually, it is called indefinitely)...

![image](https://user-images.githubusercontent.com/374656/77159384-287e5880-6a9d-11ea-9fed-5fdfe160ee33.png)

As soon as you toggle off the disable cache button, the downloading/callbacks stop.

Maybe there is nothing that can be done in this case, but development wise, it is definitely a little bit confusing!

**Comment by desandro** [comment]
Closing this one as no one else chimed in.
