### ISSUE TITLE
It doesn't work with <picture> tag?

### ISSUE THREAD

**Issue by DmitryTulchinsky** [desandro/imagesloaded#294]
Hello guys, I noticed it doesn't work with `<picture>` tag? 
Might I need specify any options for that so it recognizes `<picture>`? 
I saw only `background-img` solution in the doc though

Thanks!

**Comment by desandro** [comment]
imagesLoaded v5 has been released with proper support for `<picture>`. Please upgrade and report back if you run into any issuesl
