### ISSUE TITLE
V3 site page not found

### ISSUE THREAD

**Issue by devaping** [desandro/imagesloaded#297]
![image](https://user-images.githubusercontent.com/13602911/102179353-f0982a80-3ee1-11eb-8c55-4440bf4a0600.png)

**Comment by desandro** [comment]
Sorry about that. This is indeed an issue.

**Comment by desandro** [comment]
https://imagesloaded.desandro.com/v3 now redirects to https://github.com/desandro/imagesloaded/tree/v3.2.0#readme
