### ISSUE TITLE
Thanks for your library!

### ISSUE THREAD

**Issue by juliend2** [desandro/imagesloaded#302]
I am using it for a site I develop, and it helped me accomplish what I needed to do.
And I see that I used a few other awesome libs that you've made so it's great.

Keep up the awesome work!

**Comment by windExplorer** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by desandro** [comment]
You are welcome :)
