### ISSUE TITLE
IE occasionally aborts image load 

### ISSUE THREAD

**Issue by bluescrubbie** [desandro/imagesloaded#40]
We're using imagesloaded in a lazy-loading widget. A few of the initial images have hard coded src, the rest are inserted lazily from a data-src attribute.  On IE9, the Network Developer tab shows the lazy images aborting on the first attemp and then immediately reloading successfully.  However, the hard-coded images occasionally abort as well, and never get loaded. This happens irregularly, sometimes reloading with a clear cache 30 times before it happens again.

I can't reproduce the problem when I remove imagesloaded (the src is otherwise untouched for them).
So far, I've been unable to reproduce it on JSFiddle http://jsfiddle.net/bluescrubbie/VxFb4/12/.

I know it's obscure, but I thought I'd let you know.

**Comment by taseenb** [comment]
Same problem here on IE11. I was hiding the images with `display:none` and `visibility:hidden`. I removed both and it works. An alternative way to hide images is:

```
.hidden-images {
  position: absolute;
  z-index: -9999;
  left: -9999px;
  top: -9999px;
  width: 1px;
  height: 1px;
  overflow: hidden;
}
```

**Comment by deajan** [comment]
@taseenb Can you give a quick code example ? I don't really get what you're doing.

**Comment by taseenb** [comment]
Imagine you put all the images you need to preload in the dom:

```
<div id="images-to-preload" class="hidden-images">
    <img src="image1.jpg">
    <img src="image2.jpg">
    <img src="image3.jpg">
    <img src="image4.jpg">
</div>
```

Of course, you don't want them to be visible.
So you add the css for `.hidden-images` that will just move them off screen.
And finally you can use `imagesloaded`.

**Comment by deajan** [comment]
@taseenb Thanks... I'll try to adapt this to my drupal isotope module see if it gets my problem solved.

**Comment by dougajmcdonald** [comment]
I believe I've found the same error in my WinJS project, so I guess it's perhaps an issue going forwards

**Comment by zelenikty** [comment]
I have a similiar Issue in IE11, where I get a **Bad element for imagesLoaded null** error in the following code:
```
Imagesloaded(sliderElement.querySelector('.c-Image'), () => {
        this.slider = Slider.attachTo(
          sliderElement,
          Object.assign({}, options, { navContainer: navContainer })
        )
        this.emit('init', {
          slider: this.slider
        })
      })
```

**Comment by desandro** [comment]
I'm closing this issue as its been mostly quiet for 4 years. Please open a new issue if you run into this one.
