### ISSUE TITLE
Built File Doesn't Work w/ AMD

### ISSUE THREAD

**Issue by matthewwithanm** [desandro/imagesloaded#68]
The packaged versions of the script don't work with AMD loaders because, even though they define the dependencies ('eventEmitter' and 'eventie'), they aren't registered with a name.

``` javascript
  define( [
      'eventEmitter',
      'eventie'
    ],
    defineImagesLoaded );
```

So when this point is reached, the loader doesn't know where to find either of them.

**Comment by nitinsurana** [comment]
I have the below in require js path : 
 'imagesloaded': 'vendor/imagesloaded.pkgd',

But when I try to use r.js to optimize, it gives 
No such file or directory eventie/eventie.js

Can you please let me know how to solve ? 
Also, the readme is different (doesn't contain anything regarding eventie) than the commit link specified in one of the above comments.

**Comment by desandro** [comment]
@nitinsurana See docs, you do not need to set a path for imagesloaded if you are using the pkgd file. http://imagesloaded.desandro.com/#requirejs
