### ISSUE TITLE
Loaded Images Have Zero Height and Width

### ISSUE THREAD

**Issue by lynndylanhurley** [desandro/imagesloaded#94]
I'm trying to use this script to determine when images have finished loading so that I can draw the images to an html5 canvas.

In the 'always' callback, the image usually (not always) has a width and height of zero, which makes it impossible to set the canvas to the proper size or to draw the image with the correct parameters.

Here is the code (coffeescript):

https://gist.github.com/564ccd4410e1fccc8cb9

**Comment by Nivani** [comment]
Hmm, I seem to have this problem as well. It's not consistently reproducible, so it's hard to know if a solution actually fixes the problem. I'll let you know if I find something.

**Comment by Nivani** [comment]
I have debugged it and I can reproduce it consistently. The problem is at imagesloaded.js line 240:
`var resource = cache[ this.img.src ] || new Resource( this.img.src );`
If a resource is found in the cache but the browser decides to redownload the image anyway, imagesloaded will say these images are loaded, but actually they are not. Removing the cache fixes the problem for me:
`var resource = new Resource( this.img.src );`

**Comment by Nivani** [comment]
There is a [no-cache branch](https://github.com/desandro/imagesloaded/tree/no-cache). Using this branch fixed the problem for me.

**Comment by jackhand** [comment]
Unfortunately the no-cache branch solution didn't work for me. In my particular case, the 1st time the image loads, the width/height of the image is reported as zero (0) after the always event handler occurs. If I reload the page, the image loads just fine.

**Comment by dage** [comment]
I've found that in my case the problem can be avoided by reusing Image instances that have the same uri. When trying to track a fresh Image instance that uses a src uri that have been previously tracked, the problem happens pretty consistently on the 2nd image load when running IE 10 in debug mode from the Visual Studio debugger.

**Comment by desandro** [comment]
imagesLoaded v3.2.0 has removed the internal cache. [Try it out](http://imagesloaded.desandro.com/#install) and report back if you feel this issue has been resolved.

**Comment by madagon** [comment]
sorry for bringing this up but the problem still exists with the latest version.
random behavier, tested on apache cordova.
