### ISSUE TITLE
Tiles stack on top of each other in top left

### ISSUE THREAD

**Issue by vossavant** [desandro/imagesloaded#96]
Hi desandro,

I've been unable to get this plugin to work with Isotope. Whenever I wrap the Isotope call within the `imagesLoaded` call, the tiles stack on top of each other. That is, they are all positioned absolutely in the top left corner.

Additionally, calling isotope normally with a window.load works about half of the time. That is, sometimes the tiles stack on top of each other and sometimes they are laid out as expected.

Simply setting a `setTimeout` with a call to Isotope's `relayout` method fixes the issue, but this seems like a janky solution.

The images are not being loaded via AJAX and are already in the containing elements. Calling relayout or resizing the browser window causes the tiles to line up as expected. I'm using the "masonry" layout type, but switching to `fitRows` makes no difference.

I'm wondering if you have any idea what may be happening, or if this kind of issue has happened before.

My code, for reference:

```
$('.container').imagesLoaded( function() {
    $('.container').isotope( {
        itemSelector : '.item',
        layoutMode : 'masonry'
    } )
} );
```

Link to the site in question (scroll down to the "Feed" section by clicking "Feed" in the left sidebar):

http://factionmedia.3roadsmedia.com/

This is a staging site so it's being actively developed, but I'll leave the issue there so you can see what's happening.

Other details:
Isotope version: 1.5.25
jQuery version: 1.10.2
Browsers affected: Chrome, IE10

Firefox works about 90% of the time. The only time the tiles stack on top of each other in Firefox is on the initial page load, after a hard refresh. On subsequent page loads, the layout is fine.

Any insight you can provide is greatly appreciated. Thank you!

Ryan

**Comment by STRd6** [comment]
For anyone coming to this issue late: I had a similar problem and solved it by waiting for the `$(window).onload` event to trigger my Isotope layout.

**Comment by desandro** [comment]
Heads up: [window onload is a last resort](http://metafizzy.co/blog/window-load-last-resort/)
